"""
Post-process docx files generated by pandoc to fix table rendering issues.

Apply five fixes to all tables:
1. Width = 100% of page — table fills page width instead of being shrunk to content min-width.
2. AutoFit layout — Word allocates the 100% width across columns based on content proportions.
3. Full grid borders — every cell has top/bottom/left/right borders (matches academic-thesis style).
4. cantSplit on each row — prevent a row's content from being split across pages.
5. tblHeader on first row — repeat the header row on every page when a table spans pages.

Usage:
    python3 docs/post_process_docx.py docs/chapter04.docx [docs/chapterXX.docx ...]
"""

import sys
from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


def _ensure_tbl_pr(tbl) -> object:
    tblPr = tbl.find(qn('w:tblPr'))
    if tblPr is None:
        tblPr = OxmlElement('w:tblPr')
        tbl.insert(0, tblPr)
    return tblPr


def _set_table_width_full_page(tblPr) -> None:
    """Set table width to 100% of page width (pct type, w=5000 means 100%)."""
    tblW = tblPr.find(qn('w:tblW'))
    if tblW is None:
        tblW = OxmlElement('w:tblW')
        tblPr.append(tblW)
    tblW.set(qn('w:type'), 'pct')
    tblW.set(qn('w:w'), '5000')  # 5000 = 100% (pct unit is 50ths of a percent)


def _set_autofit_layout(tblPr) -> None:
    """Use autofit layout so columns share the 100% width by content proportion."""
    tblLayout = tblPr.find(qn('w:tblLayout'))
    if tblLayout is None:
        tblLayout = OxmlElement('w:tblLayout')
        tblPr.append(tblLayout)
    tblLayout.set(qn('w:type'), 'autofit')


def _set_full_grid_borders(tblPr) -> None:
    """Apply single black border to all six edges (outer 4 + insideH + insideV)."""
    existing = tblPr.find(qn('w:tblBorders'))
    if existing is not None:
        tblPr.remove(existing)
    tblBorders = OxmlElement('w:tblBorders')
    for edge in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
        elem = OxmlElement(f'w:{edge}')
        elem.set(qn('w:val'), 'single')
        elem.set(qn('w:sz'), '4')         # 1/2 pt (sz unit is 1/8 pt)
        elem.set(qn('w:color'), '000000')
        elem.set(qn('w:space'), '0')
        tblBorders.append(elem)
    tblPr.append(tblBorders)


def _clear_cell_widths(table) -> None:
    """Clear per-cell fixed widths so autofit can reflow."""
    for row in table.rows:
        for cell in row.cells:
            tcPr = cell._element.find(qn('w:tcPr'))
            if tcPr is not None:
                tcW = tcPr.find(qn('w:tcW'))
                if tcW is not None:
                    tcW.set(qn('w:type'), 'auto')
                    tcW.set(qn('w:w'), '0')


def _set_row_properties(table) -> None:
    """cantSplit on every row + tblHeader on the first row."""
    for row_idx, row in enumerate(table.rows):
        trPr = row._element.find(qn('w:trPr'))
        if trPr is None:
            trPr = OxmlElement('w:trPr')
            row._element.insert(0, trPr)
        if trPr.find(qn('w:cantSplit')) is None:
            trPr.append(OxmlElement('w:cantSplit'))
        if row_idx == 0 and trPr.find(qn('w:tblHeader')) is None:
            trPr.append(OxmlElement('w:tblHeader'))


def _clear_cell_first_line_indent(table) -> None:
    """
    Remove first-line indent from every paragraph inside every cell.

    The thesis body style applies a 2-character first-line indent (anti-required by
    the AGENTS.md formatting spec), which is correct for body paragraphs but wrong
    for table cells — it makes the first line of each cell offset by one character,
    misaligning visually-stacked content. We strip it here.
    """
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                pPr = para._element.find(qn('w:pPr'))
                if pPr is None:
                    pPr = OxmlElement('w:pPr')
                    para._element.insert(0, pPr)
                ind = pPr.find(qn('w:ind'))
                if ind is None:
                    ind = OxmlElement('w:ind')
                    pPr.append(ind)
                # Force zero first-line indent and zero hanging indent
                ind.set(qn('w:firstLine'), '0')
                ind.set(qn('w:firstLineChars'), '0')
                # Also zero out any hanging indent that may have been inherited
                if ind.get(qn('w:hanging')) is not None:
                    ind.set(qn('w:hanging'), '0')


def post_process(docx_path: str) -> int:
    doc = Document(docx_path)
    n_tables = len(doc.tables)

    for table in doc.tables:
        table.autofit = True
        table.allow_autofit = True
        tbl = table._element
        tblPr = _ensure_tbl_pr(tbl)

        _set_table_width_full_page(tblPr)
        _set_autofit_layout(tblPr)
        _set_full_grid_borders(tblPr)
        _clear_cell_widths(table)
        _set_row_properties(table)
        _clear_cell_first_line_indent(table)

    doc.save(docx_path)
    return n_tables


# Note: 4-level headings (####) and figure captions show a tiny square mark
# in Word's Print Layout view, in front of the paragraph. This is NOT a bullet
# point — it's Word's "Paragraph Property Indicator", shown when a paragraph
# has the `<w:keepNext/>` attribute (meaning "do not split from next paragraph
# across pages"). The Heading4 style and CaptionedFigure style in
# docs/antai-template.docx both define keepNext, so the mark appears.
#
# This indicator only shows in Word's editing view and does NOT appear in
# print or PDF export. To hide it during editing, turn off Word's "Show
# formatting marks" (Home → ¶ button, or Preferences → View → uncheck All).
#
# We do NOT strip keepNext from the styles, because removing it would cause
# unwanted page breaks between headings/captions and their following content.


if __name__ == '__main__':
    for path in sys.argv[1:]:
        n = post_process(path)
        print(f"Post-processed {path}: {n} tables")
