"""
Post-process docx files generated by pandoc to fix table rendering issues.

Apply five fixes to all tables:
1. Width = 100% of page — table fills page width instead of being shrunk to content min-width.
2. AutoFit layout — Word allocates the 100% width across columns based on content proportions.
3. Full grid borders — every cell has top/bottom/left/right borders (matches academic-thesis style).
4. cantSplit on each row — prevent a row's content from being split across pages.
5. tblHeader on first row — repeat the header row on every page when a table spans pages.

Usage:
    python3 docs/post_process_docx.py docs/chapter04.docx [docs/chapterXX.docx ...]
"""

import os
import sys
from docx import Document
from docx.shared import Cm, Pt
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


def _ensure_tbl_pr(tbl) -> object:
    tblPr = tbl.find(qn('w:tblPr'))
    if tblPr is None:
        tblPr = OxmlElement('w:tblPr')
        tbl.insert(0, tblPr)
    return tblPr


def _set_table_width_full_page(tblPr) -> None:
    """Set table width to 100% of page width (pct type, w=5000 means 100%)."""
    tblW = tblPr.find(qn('w:tblW'))
    if tblW is None:
        tblW = OxmlElement('w:tblW')
        tblPr.append(tblW)
    tblW.set(qn('w:type'), 'pct')
    tblW.set(qn('w:w'), '5000')  # 5000 = 100% (pct unit is 50ths of a percent)


def _set_autofit_layout(tblPr) -> None:
    """Use autofit layout so columns share the 100% width by content proportion."""
    tblLayout = tblPr.find(qn('w:tblLayout'))
    if tblLayout is None:
        tblLayout = OxmlElement('w:tblLayout')
        tblPr.append(tblLayout)
    tblLayout.set(qn('w:type'), 'autofit')


def _set_full_grid_borders(tblPr) -> None:
    """Apply single black border to all six edges (outer 4 + insideH + insideV)."""
    existing = tblPr.find(qn('w:tblBorders'))
    if existing is not None:
        tblPr.remove(existing)
    tblBorders = OxmlElement('w:tblBorders')
    for edge in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
        elem = OxmlElement(f'w:{edge}')
        elem.set(qn('w:val'), 'single')
        elem.set(qn('w:sz'), '4')         # 1/2 pt (sz unit is 1/8 pt)
        elem.set(qn('w:color'), '000000')
        elem.set(qn('w:space'), '0')
        tblBorders.append(elem)
    tblPr.append(tblBorders)


def _clear_cell_widths(table) -> None:
    """Clear per-cell fixed widths so autofit can reflow."""
    for row in table.rows:
        for cell in row.cells:
            tcPr = cell._element.find(qn('w:tcPr'))
            if tcPr is not None:
                tcW = tcPr.find(qn('w:tcW'))
                if tcW is not None:
                    tcW.set(qn('w:type'), 'auto')
                    tcW.set(qn('w:w'), '0')


def _set_row_properties(table) -> None:
    """cantSplit on every row + tblHeader on the first row."""
    for row_idx, row in enumerate(table.rows):
        trPr = row._element.find(qn('w:trPr'))
        if trPr is None:
            trPr = OxmlElement('w:trPr')
            row._element.insert(0, trPr)
        if trPr.find(qn('w:cantSplit')) is None:
            trPr.append(OxmlElement('w:cantSplit'))
        if row_idx == 0 and trPr.find(qn('w:tblHeader')) is None:
            trPr.append(OxmlElement('w:tblHeader'))


def _clear_cell_first_line_indent(table) -> None:
    """
    Remove first-line indent from every paragraph inside every cell.

    The thesis body style applies a 2-character first-line indent (anti-required by
    the AGENTS.md formatting spec), which is correct for body paragraphs but wrong
    for table cells — it makes the first line of each cell offset by one character,
    misaligning visually-stacked content. We strip it here.
    """
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                pPr = para._element.find(qn('w:pPr'))
                if pPr is None:
                    pPr = OxmlElement('w:pPr')
                    para._element.insert(0, pPr)
                ind = pPr.find(qn('w:ind'))
                if ind is None:
                    ind = OxmlElement('w:ind')
                    pPr.append(ind)
                # Force zero first-line indent and zero hanging indent
                ind.set(qn('w:firstLine'), '0')
                ind.set(qn('w:firstLineChars'), '0')
                # Also zero out any hanging indent that may have been inherited
                if ind.get(qn('w:hanging')) is not None:
                    ind.set(qn('w:hanging'), '0')


def _make_para(text, *, size_pt, bold=False, align='center', font_cjk='黑体',
               space_before_pt=0, space_after_pt=0, underline=False,
               line=360):
    """Build a standalone <w:p> with a single styled run (or empty if text is '').
    line: 行距（240=单倍，360=1.5倍）。"""
    p = OxmlElement('w:p')
    pPr = OxmlElement('w:pPr')
    jc = OxmlElement('w:jc'); jc.set(qn('w:val'), align); pPr.append(jc)
    spacing = OxmlElement('w:spacing')
    spacing.set(qn('w:before'), str(int(space_before_pt * 20)))
    spacing.set(qn('w:after'), str(int(space_after_pt * 20)))
    spacing.set(qn('w:line'), str(line)); spacing.set(qn('w:lineRule'), 'auto')
    pPr.append(spacing)
    ind = OxmlElement('w:ind')
    ind.set(qn('w:firstLine'), '0'); ind.set(qn('w:firstLineChars'), '0')
    pPr.append(ind)
    p.append(pPr)
    if text:
        r = OxmlElement('w:r')
        rPr = OxmlElement('w:rPr')
        rfonts = OxmlElement('w:rFonts')
        rfonts.set(qn('w:ascii'), 'Times New Roman')
        rfonts.set(qn('w:hAnsi'), 'Times New Roman')
        rfonts.set(qn('w:eastAsia'), font_cjk)
        rPr.append(rfonts)
        if bold:
            rPr.append(OxmlElement('w:b')); rPr.append(OxmlElement('w:bCs'))
        if underline:
            u = OxmlElement('w:u'); u.set(qn('w:val'), 'single'); rPr.append(u)
        sz = OxmlElement('w:sz'); sz.set(qn('w:val'), str(int(size_pt * 2)))
        szCs = OxmlElement('w:szCs'); szCs.set(qn('w:val'), str(int(size_pt * 2)))
        rPr.append(sz); rPr.append(szCs)
        r.append(rPr)
        t = OxmlElement('w:t'); t.set(qn('xml:space'), 'preserve'); t.text = text
        r.append(t)
        p.append(r)
    return p


def _make_field_row(label, value):
    """Cover field line: '标签：____value____'。
    整块左对齐 + 固定左缩进（让字段块作为整体在页面居中），
    标签右补全角空格到 4 字宽，使各行冒号竖直对齐。
    """
    # 标签规整到等宽：以最长标签"学科/专业"(5 字)为基准，其余右侧补全角空格
    label_plain = label.replace('　', '')  # 去掉已有的对齐空格
    pad = max(0, 4 - len(label_plain))      # 4 字标签补到等宽
    if len(label_plain) >= 4:
        label_fmt = label                   # "学科/专业""申请学位"等不再加空格
    else:
        # 在标签字符间均匀插入全角空格凑到 4 字宽（如 姓名→姓　　名）
        if len(label_plain) == 2:
            label_fmt = label_plain[0] + '　　' + label_plain[1]
        else:
            label_fmt = label_plain + '　' * pad

    p = OxmlElement('w:p')
    pPr = OxmlElement('w:pPr')
    jc = OxmlElement('w:jc'); jc.set(qn('w:val'), 'left'); pPr.append(jc)
    # 固定左缩进，使左对齐的字段块整体在页面居中
    ind = OxmlElement('w:ind')
    ind.set(qn('w:left'), '2600'); ind.set(qn('w:firstLine'), '0')
    ind.set(qn('w:firstLineChars'), '0'); pPr.append(ind)
    spacing = OxmlElement('w:spacing')
    spacing.set(qn('w:after'), '160'); spacing.set(qn('w:line'), '300')
    spacing.set(qn('w:lineRule'), 'auto'); pPr.append(spacing)
    p.append(pPr)
    for txt, ul in ((label_fmt + '：', False), (value, True)):
        r = OxmlElement('w:r')
        rPr = OxmlElement('w:rPr')
        rfonts = OxmlElement('w:rFonts')
        rfonts.set(qn('w:ascii'), 'Times New Roman')
        rfonts.set(qn('w:hAnsi'), 'Times New Roman')
        rfonts.set(qn('w:eastAsia'), '黑体')
        rPr.append(rfonts)
        if ul:
            u = OxmlElement('w:u'); u.set(qn('w:val'), 'single'); rPr.append(u)
        sz = OxmlElement('w:sz'); sz.set(qn('w:val'), '28')
        szCs = OxmlElement('w:szCs'); szCs.set(qn('w:val'), '28')
        rPr.append(sz); rPr.append(szCs)
        r.append(rPr)
        t = OxmlElement('w:t'); t.set(qn('xml:space'), 'preserve'); t.text = txt
        r.append(t)
        p.append(r)
    return p


def _make_logo_para(doc, img_path, width_cm=3.6, space_after_pt=12):
    """居中插入校徽图片，返回该段落的 <w:p>。"""
    # 借助一个临时段落让 python-docx 完成图片嵌入与关系注册
    tmp = doc.add_paragraph()
    run = tmp.add_run()
    run.add_picture(img_path, width=Cm(width_cm))
    p_el = tmp._element
    p_el.getparent().remove(p_el)  # 从文档末尾摘出，稍后插到封面
    # 居中
    pPr = p_el.get_or_add_pPr()
    jc = OxmlElement('w:jc'); jc.set(qn('w:val'), 'center'); pPr.append(jc)
    spacing = OxmlElement('w:spacing')
    spacing.set(qn('w:after'), str(int(space_after_pt * 20))); pPr.append(spacing)
    return p_el


def _make_page_break():
    p = OxmlElement('w:p')
    r = OxmlElement('w:r')
    br = OxmlElement('w:br'); br.set(qn('w:type'), 'page')
    r.append(br)
    p.append(r)
    return p


def _base_sectpr_xml(extra=''):
    """生成一个完整的 sectPr XML 字符串（继承模板页面设置 + 页眉页脚引用占位）。

    sectPr 必须包含页面尺寸/边距，否则 Word 会回退到默认 A4 边距。
    extra 用于追加 titlePg / pgNumType 等差异化设置。
    """
    return (
        '<w:sectPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:pgSz w:w="11906" w:h="16838"/>'
        '<w:pgMar w:top="1985" w:right="1418" w:bottom="2268" w:left="1418" '
        'w:header="1418" w:footer="1701" w:gutter="0"/>'
        f'{extra}'
        '</w:sectPr>'
    )


def _make_section_para(sectpr_xml):
    """生成一个仅承载节属性的空段落（OOXML：节属性写在该节末段的 pPr 内）。"""
    from docx.oxml import parse_xml
    p = OxmlElement('w:p')
    pPr = OxmlElement('w:pPr')
    pPr.append(parse_xml(sectpr_xml))
    p.append(pPr)
    return p


# 封面与页眉信息从外部 JSON 加载（docs/thesis-meta.json），
# 同学复用本模板时只需改 JSON，无需动本脚本。找不到时回退到内置默认值。
_META_PATH = os.path.join(os.path.dirname(__file__), 'thesis-meta.json')

_DEFAULT_META = {
    'school_line': '上海交通大学硕士学位论文',
    'title': '论文题目占位（请在 docs/thesis-meta.json 中修改）',
    'english_lines': [
        'A Dissertation Submitted to',
        'Shanghai Jiao Tong University',
        'for the Degree of Master of Business Administration',
    ],
    'fields': [
        ['姓　　名', '张　三'],
        ['学　　号', '0000000000'],
        ['导　　师', '某某　教授'],
        ['院　　系', '安泰经济与管理学院'],
        ['学科/专业', '工商管理（MBA）'],
        ['申请学位', '工商管理硕士'],
    ],
    'date': '20XX 年 XX 月',
    'header_left': '上海交通大学MBA学位论文',
    'header_title': '论文题目占位（请在 docs/thesis-meta.json 中修改）',
    'frontmatter_header_right': '摘　要',
    'toc_header_right': '目　录',
}


def _load_meta():
    import json
    meta = dict(_DEFAULT_META)
    if os.path.exists(_META_PATH):
        with open(_META_PATH, encoding='utf-8') as f:
            data = json.load(f)
        meta.update({k: v for k, v in data.items() if not k.startswith('_')})
    return meta


META = _load_meta()
# 兼容旧引用：COVER 沿用 title/fields/date 三个键
COVER = {'title': META['title'], 'fields': META['fields'], 'date': META['date']}


LOGO_PATH = os.path.join(os.path.dirname(__file__), 'figures', 'sjtu-logo.png')

# 原创性声明与版权授权书正文（逐字取自安泰官方格式样本）
DECLARATION_TEXT = (
    '本人郑重声明：所呈交的学位论文，是本人在导师的指导下，独立进行研究工作'
    '所取得的成果。除文中已经注明引用的内容外，本论文不包含任何其他个人或集体'
    '已经发表或撰写过的作品成果。对本文的研究做出重要贡献的个人和集体，均已在'
    '文中以明确方式标明。本人完全意识到本声明的法律结果由本人承担。'
)
AUTHORIZATION_TEXT = (
    '本学位论文作者完全了解学校有关保留、使用学位论文的规定，同意学校保留并向'
    '国家有关部门或机构送交论文的复印件和电子版，允许论文被查阅和借阅。'
)


def _build_declaration_elements():
    """原创性声明页 + 版权使用授权书页（封面后、摘要前）。"""
    els = []
    # —— 原创性声明页 ——
    els.append(_make_para('', size_pt=10.5, space_after_pt=24))
    els.append(_make_para('上海交通大学', size_pt=16, bold=True, font_cjk='黑体',
                          space_after_pt=6))
    els.append(_make_para('学位论文原创性声明', size_pt=16, bold=True,
                          font_cjk='黑体', space_after_pt=24))
    p = _make_para(DECLARATION_TEXT, size_pt=12, font_cjk='宋体', align='both',
                   space_after_pt=36)
    # 正文首行缩进 2 字符
    pPr = p.find(qn('w:pPr'))
    ind = pPr.find(qn('w:ind'))
    ind.set(qn('w:firstLine'), '480'); ind.set(qn('w:firstLineChars'), '200')
    els.append(p)
    els.append(_make_para('学位论文作者签名：', size_pt=14, font_cjk='宋体',
                          align='right', space_after_pt=12))
    els.append(_make_para('日期：    年   月   日', size_pt=14, font_cjk='宋体',
                          align='right', space_after_pt=0))
    els.append(_make_page_break())
    # —— 版权使用授权书页 ——
    els.append(_make_para('', size_pt=10.5, space_after_pt=24))
    els.append(_make_para('上海交通大学', size_pt=16, bold=True, font_cjk='黑体',
                          space_after_pt=6))
    els.append(_make_para('学位论文使用授权书', size_pt=16, bold=True,
                          font_cjk='黑体', space_after_pt=24))
    p2 = _make_para(AUTHORIZATION_TEXT, size_pt=12, font_cjk='宋体', align='both',
                    space_after_pt=18)
    pPr2 = p2.find(qn('w:pPr'))
    ind2 = pPr2.find(qn('w:ind'))
    ind2.set(qn('w:firstLine'), '480'); ind2.set(qn('w:firstLineChars'), '200')
    els.append(p2)
    els.append(_make_para('本学位论文属于　□公开论文', size_pt=10.5,
                          font_cjk='宋体', align='left', space_after_pt=4))
    els.append(_make_para('　　　　　　　　□内部论文，□1年/□2年/□3年　解密后适用本授权书。',
                          size_pt=10.5, font_cjk='宋体', align='left', space_after_pt=4))
    els.append(_make_para('　　　　　　　　□秘密论文，　　年（不超过10年）解密后适用本授权书。',
                          size_pt=10.5, font_cjk='宋体', align='left', space_after_pt=4))
    els.append(_make_para('　　　　　　　　□机密论文，　　年（不超过20年）解密后适用本授权书。',
                          size_pt=10.5, font_cjk='宋体', align='left', space_after_pt=4))
    els.append(_make_para('（请在以上方框内打“√”）', size_pt=10.5, bold=True,
                          font_cjk='宋体', align='left', space_after_pt=36))
    els.append(_make_para('学位论文作者签名：　　　　　　　指导教师签名：',
                          size_pt=14, font_cjk='宋体', align='left', space_after_pt=12))
    els.append(_make_para('日期：　 年　 月　 日　　　　　 日期：　 年　 月　 日',
                          size_pt=14, font_cjk='宋体', align='left', space_after_pt=0))
    els.append(_make_page_break())
    return els


def _build_cover_elements(doc):
    """封面布局 —— 严格照安泰官方模板：无校徽；中文题目二号(22pt)黑体加粗居中；
    英文题目二号黑体加粗大写居中；字段三号(16pt)黑体居中。
    版式：首行下空 3 行 → 中文题目 → 空 1 行 → 英文题目 → 空 6 行 → 字段。
    """
    # 单倍行距，确保单页容纳（参照案例封面比例）
    els = []
    # 首行下空 2 行
    for _ in range(2):
        els.append(_make_para('', size_pt=12, line=240))
    # 中文题目（二号 22pt 黑体加粗居中，可两行）
    for line in META['title'].split('\n'):
        els.append(_make_para(line, size_pt=22, bold=True, font_cjk='黑体',
                              space_after_pt=2, line=300))
    # 空 1 行
    els.append(_make_para('', size_pt=10, line=240))
    # 英文题目（小三 15pt 黑体加粗大写居中，案例中英文明显小于中文，可多行）
    for line in META.get('english_title', '').split('\n'):
        els.append(_make_para(line.upper(), size_pt=15, bold=True,
                              font_cjk='黑体', space_after_pt=2, line=280))
    # 空 3 行
    for _ in range(3):
        els.append(_make_para('', size_pt=12, line=240))
    # 字段（三号 16pt 黑体，左对齐成块、整体缩进使其居中偏左，冒号竖直对齐）
    for label, value in META['fields']:
        p = _make_para(f'{label}：{value}', size_pt=16, bold=False,
                       font_cjk='黑体', align='left', space_after_pt=6, line=300)
        pPr = p.find(qn('w:pPr'))
        ind = pPr.find(qn('w:ind'))
        ind.set(qn('w:left'), '2600')   # 左缩进约 4.6cm，使字段块居中偏左
        els.append(p)
    els.append(_make_page_break())
    return els


def _section_para_carrying(sectpr_el):
    """把一个 sectPr 元素塞进新空段落的 pPr —— 该段落即成为某节的末段（分节符）。"""
    p = OxmlElement('w:p')
    pPr = OxmlElement('w:pPr')
    pPr.append(sectpr_el)
    p.append(pPr)
    return p


def _set_pgnumtype(sectpr, fmt=None, start=None):
    """设置/替换节的页码格式与起始值。"""
    old = sectpr.find(qn('w:pgNumType'))
    if old is not None:
        sectpr.remove(old)
    el = OxmlElement('w:pgNumType')
    if fmt:
        el.set(qn('w:fmt'), fmt)
    if start is not None:
        el.set(qn('w:start'), str(start))
    # pgNumType 在 sectPr 中的合法位置靠后，append 即可
    sectpr.append(el)


def _add_titlepg(sectpr):
    """封面节首页特殊：无页眉页脚（未定义 first-page 引用时即为空）。"""
    if sectpr.find(qn('w:titlePg')) is None:
        sectpr.append(OxmlElement('w:titlePg'))


def _build_toc_elements():
    """目录标题 + Word TOC 域（打开后右键更新域生成页码）。
    注：不含前导分页符——目录前的分节符已负责分页。"""
    els = [_make_para('目　录', size_pt=16, bold=True, font_cjk='黑体',
                      space_after_pt=18)]
    # 复杂域: begin / instrText / separate / placeholder / end
    p = OxmlElement('w:p')

    def run_fld(child):
        r = OxmlElement('w:r'); r.append(child); return r

    begin = OxmlElement('w:fldChar')
    begin.set(qn('w:fldCharType'), 'begin'); begin.set(qn('w:dirty'), 'true')
    instr = OxmlElement('w:instrText')
    instr.set(qn('xml:space'), 'preserve')
    instr.text = 'TOC \\o "1-3" \\h \\z \\u '
    sep = OxmlElement('w:fldChar'); sep.set(qn('w:fldCharType'), 'separate')
    ph = OxmlElement('w:r')
    pht = OxmlElement('w:t'); pht.set(qn('xml:space'), 'preserve')
    pht.text = '（在 Word 中右键此处选择“更新域”→“更新整个目录”以生成目录）'
    ph.append(pht)
    end = OxmlElement('w:fldChar'); end.set(qn('w:fldCharType'), 'end')
    for c in (begin, instr, sep):
        p.append(run_fld(c))
    p.append(ph)
    p.append(run_fld(end))
    els.append(p)
    return els


def _enable_update_fields(doc):
    """让 Word 打开文档时提示更新域（目录页码自动生成）。"""
    settings = doc.settings.element
    if settings.find(qn('w:updateFields')) is None:
        uf = OxmlElement('w:updateFields'); uf.set(qn('w:val'), 'true')
        settings.append(uf)


# 正文章节标题（这些 Heading 1 各自成节，页眉右侧写死本节标题）
_BODY_CHAPTER_PREFIXES = ('第一章', '第二章', '第三章', '第四章', '第五章',
                          '第六章', '第七章', '附录', '参考文献')


def _split_body_into_sections(doc):
    """把正文按章切成多个 section（在每个章标题前插入分节符）。
    返回 [(章标题文本, 该章对应的 sectPr 元素), ...]，供随后逐节填页眉。
    """
    import copy
    body = doc.element.body
    body_sectpr = body.find(qn('w:sectPr'))

    # 找到所有正文章标题段落（按文档顺序）
    chapter_paras = []
    for p in doc.paragraphs:
        if p.style and p.style.name == 'Heading 1' and \
                p.text.strip().startswith(_BODY_CHAPTER_PREFIXES):
            chapter_paras.append(p)

    # 在第 2..N 个章标题前各插一个分节符段落，让上一章在此结束成节。
    # 第 1 个章标题（第一章）前已有"前置节分节符"（由 add_frontmatter 插入），不再插。
    # 每个分节符继承正文页面设置 + 阿拉伯页码（仅首节 start=1，其余不重启）。
    section_markers = []  # (上一章标题文本, sectPr元素)
    for idx in range(1, len(chapter_paras)):
        prev_title = chapter_paras[idx - 1].text.strip()
        sectpr = copy.deepcopy(body_sectpr)
        # 第一章（idx==1 承载的是第 1 章节属性）阿拉伯页码从 1 重启，其余续页
        if idx == 1:
            _set_pgnumtype(sectpr, fmt='decimal', start=1)
        else:
            _set_pgnumtype(sectpr, fmt='decimal')
        marker = _section_para_carrying(sectpr)
        chapter_paras[idx]._element.addprevious(marker)
        section_markers.append((prev_title, sectpr))
    # 最后一章用 body 末尾的 body_sectpr（续页，不重启）
    _set_pgnumtype(body_sectpr, fmt='decimal')
    section_markers.append((chapter_paras[-1].text.strip(), body_sectpr))
    return section_markers


def _header_xml(right_text, right=True):
    """构造一个完整 header part 的 XML（左=校名 tab 右=章名，底部横线）。
    right=False 时只显示左侧校名（用于摘要/目录等前置页）。
    """
    right_part = (
        '<w:r><w:tab/></w:r>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" '
        'w:eastAsia="宋体"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr>'
        f'<w:t xml:space="preserve">{right_text}</w:t></w:r>'
    ) if right else ''
    return (
        '<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:p><w:pPr>'
        '<w:pStyle w:val="Header"/>'
        '<w:ind w:firstLine="0" w:firstLineChars="0" w:left="0"/>'
        '<w:tabs><w:tab w:val="right" w:pos="9072"/></w:tabs>'
        '<w:pBdr><w:bottom w:val="single" w:sz="4" w:space="1" w:color="000000"/></w:pBdr>'
        '</w:pPr>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" '
        'w:eastAsia="宋体"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr>'
        f'<w:t xml:space="preserve">{META["header_left"]}</w:t></w:r>'
        f'{right_part}'
        '</w:p></w:hdr>'
    )


def _set_section_header(doc, section, right_text, right=True):
    """为单个 section 创建独立 header part 并写入页眉（左=校名，右=本章标题）。

    通过 DocumentPart.add_header_part() 新建独立 part，再把本节 sectPr 的
    默认 headerReference 重指向它——避免所有节共享同一个 header1.xml。
    """
    from docx.oxml import parse_xml
    sectpr = section._sectPr
    # 移除本节已有的 default headerReference（指向共享的 header1.xml）
    for ref in sectpr.findall(qn('w:headerReference')):
        if ref.get(qn('w:type')) in ('default', None):
            sectpr.remove(ref)
    # 新建独立 header part
    header_part, rId = doc.part.add_header_part()
    hdr = header_part._element
    # 清空默认内容，写入目标段落（修改子节点而非替换根元素，确保被正确序列化）
    for child in list(hdr):
        hdr.remove(child)
    target = parse_xml(_header_xml(right_text, right=right))
    for child in list(target):
        hdr.append(child)
    # 在 sectPr 顶部插入指向新 part 的 default headerReference
    ref = OxmlElement('w:headerReference')
    ref.set(qn('w:type'), 'default')
    ref.set(qn('r:id'), rId)
    sectpr.insert(0, ref)


def add_frontmatter(doc) -> None:
    """在文档最前插入封面页 + 目录，并建立三节分段页码：
       封面节（首页无页眉页脚）→ 前置节（摘要/Abstract/目录，罗马数字 Ⅰ起）
       → 正文节（第一章起，阿拉伯数字 1 起）。
    """
    import copy
    # pandoc 由 frontmatter title/author 生成的 Title/Author 段落与封面重复，删除
    for p in list(doc.paragraphs):
        if p.style and p.style.name in ('Title', 'Author'):
            p._element.getparent().remove(p._element)

    body = doc.element.body
    body_sectpr = body.find(qn('w:sectPr'))  # 文档级 sectPr = 正文节属性

    # 正文节：阿拉伯数字，从 1 重启
    _set_pgnumtype(body_sectpr, fmt='decimal', start=1)

    # 锚点 1：文档第一个段落（摘要标题）→ 封面插到它前面
    first_anchor = doc.paragraphs[0]._element
    cover_els = _build_cover_elements(doc)
    # 封面后紧跟原创性声明页 + 版权使用授权书页（同属封面节，无页码）
    cover_els.extend(_build_declaration_elements())
    # 移除末尾的纯分页符，改用封面节分节符承载
    if cover_els and cover_els[-1].find(qn('w:r')) is not None and \
            cover_els[-1].find('.//' + qn('w:br')) is not None:
        cover_els = cover_els[:-1]
    # 封面节 sectPr：复制正文页面设置，加 titlePg（首页空页眉脚），页码不显示
    cover_sectpr = copy.deepcopy(body_sectpr)
    _set_pgnumtype(cover_sectpr, fmt='upperRoman')  # 占位，封面首页因 titlePg 不显示
    _add_titlepg(cover_sectpr)
    cover_els.append(_section_para_carrying(cover_sectpr))
    for el in cover_els:
        first_anchor.addprevious(el)

    # 锚点 2：第一章标题 → 目录 + 前置节分节符插到它前面
    ch1_anchor = None
    for p in doc.paragraphs:
        if p.style and p.style.name.startswith('Heading 1') and \
                p.text.strip().startswith('第一章'):
            ch1_anchor = p._element
            break
    if ch1_anchor is None:
        raise RuntimeError('未找到“第一章”标题，无法定位目录插入点')
    # 前置区拆成两个子节：
    #   摘要节（摘要 + Abstract）页眉右侧"摘　要"
    #   目录节（目录）页眉右侧"目　录"
    # 摘要节 sectPr：罗马数字从 Ⅰ 起，承载在"目录前的分节符"上
    abstract_sectpr = copy.deepcopy(body_sectpr)
    _set_pgnumtype(abstract_sectpr, fmt='upperRoman', start=1)
    # 目录节 sectPr：续罗马数字（不重启），承载在第一章前的分节符上
    toc_sectpr = copy.deepcopy(body_sectpr)
    _set_pgnumtype(toc_sectpr, fmt='upperRoman')

    toc_els = _build_toc_elements()
    # 在目录标题最前插入"摘要节分节符"，使摘要+Abstract 成为独立一节
    toc_els.insert(0, _section_para_carrying(abstract_sectpr))
    # 目录节末尾（第一章前）插入"目录节分节符"
    toc_els.append(_section_para_carrying(toc_sectpr))
    for el in toc_els:
        ch1_anchor.addprevious(el)

    # 摘要节（index 1）、目录节（index 2）按模板不加页眉：清空其页眉内容
    for idx in (1, 2):
        sec = doc.sections[idx]
        hdr = sec.header
        hdr.is_linked_to_previous = False
        for p in list(hdr.paragraphs):
            p.clear()

    # 正文按章分节（分节用于分段页码）；按纲领，每节页眉右侧统一写论文题目。
    section_markers = _split_body_into_sections(doc)
    # 分节后 sections 顺序固定为：[封面, 摘要, 目录, 章1, 章2, ..., 末章]
    # 正文节从 index 3 开始。页眉右侧统一为论文题目（纲领要求）。
    body_sections = doc.sections[3:]
    for section in body_sections:
        _set_section_header(doc, section, META['header_title'])

    # 封面节（封面 + 声明 + 授权页）：首页与后续页的页眉页脚均清空，
    # 确保整节无页眉横线、无页码（属前置部分，不编页码）。
    cover_section = doc.sections[0]
    cover_section.different_first_page_header_footer = True
    for hf in (cover_section.first_page_header, cover_section.first_page_footer,
               cover_section.header, cover_section.footer):
        hf.is_linked_to_previous = False
        for p in list(hf.paragraphs):
            p.clear()

    # 除封面节(0)外，所有节注入居中 PAGE 页码域（摘要/目录罗马、正文阿拉伯，
    # 页码格式由各节 pgNumType 决定）。封面节保持无页码。
    for sec in doc.sections[1:]:
        _set_section_footer_pagenum(doc, sec)

    _enable_update_fields(doc)


def post_process(docx_path: str, with_cover: bool = False) -> int:
    doc = Document(docx_path)
    n_tables = len(doc.tables)

    for table in doc.tables:
        table.autofit = True
        table.allow_autofit = True
        tbl = table._element
        tblPr = _ensure_tbl_pr(tbl)

        _set_table_width_full_page(tblPr)
        _set_autofit_layout(tblPr)
        _set_full_grid_borders(tblPr)
        _clear_cell_widths(table)
        _set_row_properties(table)
        _clear_cell_first_line_indent(table)

    _enforce_fonts(doc)
    _style_table_captions(doc)

    if with_cover:
        add_frontmatter(doc)

    doc.save(docx_path)
    return n_tables


import re as _re

_TABLE_CAP_RE = _re.compile(r'^表\s*\d+-\d+\s')

# 样式 → 中文字体映射（纲领：标题黑体、正文宋体、图题楷体）。
# 显式写死每个 run 的 eastAsia，根除 Word 在无显式字体时回退到"等线"的问题。
_STYLE_FONT = {
    'Heading 1': '黑体', 'Heading 2': '黑体', 'Heading 3': '黑体',
    'Heading 4': '黑体', 'Heading 5': '黑体',
    'Image Caption': '楷体',  # 图题楷体
    'Normal': '宋体', 'Body Text': '宋体', 'First Paragraph': '宋体',
    'Compact': '宋体', 'Bibliography': '宋体',
}


def _footer_pagenum_xml():
    """构造含居中 PAGE 域的页脚 XML（页码居中，五号 Times New Roman）。"""
    return (
        '<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:p><w:pPr>'
        '<w:pStyle w:val="Footer"/>'
        '<w:jc w:val="center"/>'
        '<w:ind w:firstLine="0" w:firstLineChars="0" w:left="0"/>'
        '</w:pPr>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        '<w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr>'
        '<w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        '<w:sz w:val="21"/></w:rPr>'
        '<w:instrText xml:space="preserve"> PAGE \\* MERGEFORMAT </w:instrText></w:r>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        '<w:sz w:val="21"/></w:rPr><w:fldChar w:fldCharType="separate"/></w:r>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        '<w:sz w:val="21"/></w:rPr><w:t>1</w:t></w:r>'
        '<w:r><w:rPr><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman"/>'
        '<w:sz w:val="21"/></w:rPr><w:fldChar w:fldCharType="end"/></w:r>'
        '</w:p></w:ftr>'
    )


def _set_section_footer_pagenum(doc, section):
    """为某节创建独立 footer part 并写入居中 PAGE 页码域。"""
    from docx.oxml import parse_xml
    sectpr = section._sectPr
    for ref in sectpr.findall(qn('w:footerReference')):
        if ref.get(qn('w:type')) in ('default', None):
            sectpr.remove(ref)
    footer_part, rId = doc.part.add_footer_part()
    ftr = footer_part._element
    for child in list(ftr):
        ftr.remove(child)
    target = parse_xml(_footer_pagenum_xml())
    for child in list(target):
        ftr.append(child)
    ref = OxmlElement('w:footerReference')
    ref.set(qn('w:type'), 'default')
    ref.set(qn('r:id'), rId)
    # footerReference 须在 headerReference 之后、sectPr 较前位置
    sectpr.insert(0, ref)


def _set_run_font(r, font):
    rpr = r._element.get_or_add_rPr()
    rf = rpr.find(qn('w:rFonts'))
    if rf is None:
        rf = OxmlElement('w:rFonts'); rpr.insert(0, rf)
    rf.set(qn('w:eastAsia'), font)
    rf.set(qn('w:ascii'), 'Times New Roman')
    rf.set(qn('w:hAnsi'), 'Times New Roman')


def _enforce_fonts(doc):
    """给每个 run 显式写死中文字体（eastAsia），不依赖样式继承——
    根除 Word 在无显式字体时回退到"等线"的问题。覆盖正文段落 + 表格单元格。
    """
    # 正文段落（按样式映射）
    for p in doc.paragraphs:
        font = _STYLE_FONT.get(p.style.name)
        if font is None:
            continue
        for r in p.runs:
            _set_run_font(r, font)
    # 表格单元格内容（统一宋体——表格属正文）
    for t in doc.tables:
        for row in t.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    for r in p.runs:
                        _set_run_font(r, '宋体')


def _style_table_captions(doc):
    """把表名段落（如“表 5-1 ……”，加粗、整段为表名）改为五号楷体居中。
    纲领：表题五号楷体，写在表格正上方居中。仅处理加粗的表名段，不动正文中
    提及表号的普通句子。
    """
    for p in doc.paragraphs:
        t = p.text.strip()
        if not _TABLE_CAP_RE.match(t):
            continue
        runs = p.runs
        if not runs or not any(r.font.bold for r in runs):
            continue  # 正文提及句（非加粗）跳过
        # 居中
        pPr = p._element.get_or_add_pPr()
        for jc in pPr.findall(qn('w:jc')):
            pPr.remove(jc)
        jc = OxmlElement('w:jc'); jc.set(qn('w:val'), 'center'); pPr.append(jc)
        # 每个 run 改楷体五号、去加粗
        for r in runs:
            r.font.bold = False
            r.font.size = Pt(10.5)  # 五号
            rpr = r._element.get_or_add_rPr()
            rf = rpr.find(qn('w:rFonts'))
            if rf is None:
                rf = OxmlElement('w:rFonts'); rpr.insert(0, rf)
            rf.set(qn('w:eastAsia'), '楷体')
            rf.set(qn('w:ascii'), 'Times New Roman')
            rf.set(qn('w:hAnsi'), 'Times New Roman')


# Note: 4-level headings (####) and figure captions show a tiny square mark
# in Word's Print Layout view, in front of the paragraph. This is NOT a bullet
# point — it's Word's "Paragraph Property Indicator", shown when a paragraph
# has the `<w:keepNext/>` attribute (meaning "do not split from next paragraph
# across pages"). The Heading4 style and CaptionedFigure style in
# docs/antai-template.docx both define keepNext, so the mark appears.
#
# This indicator only shows in Word's editing view and does NOT appear in
# print or PDF export. To hide it during editing, turn off Word's "Show
# formatting marks" (Home → ¶ button, or Preferences → View → uncheck All).
#
# We do NOT strip keepNext from the styles, because removing it would cause
# unwanted page breaks between headings/captions and their following content.


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--cover']
    with_cover = '--cover' in sys.argv[1:]
    for path in args:
        n = post_process(path, with_cover=with_cover)
        extra = ' + 封面/目录' if with_cover else ''
        print(f"Post-processed {path}: {n} tables{extra}")
